name: Tests, Linter & Typecheck

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: "Tests & Typechecking: ${{ matrix.os }} (node@${{ matrix.node_version }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16.7]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ runner.node_version }}
          cache: npm

      - name: Install NPM dependencies
        run: npm install

      - name: Run Type Checking & ESLint
        run: npm run check

      - name: Test
        run: npm run test
        working-directory: packages/wrangler
